<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Crea una nueva cuenta' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Delete' => '',
    'Info Requests' => '',
    'Ingresa en tu cuenta de usuario' => '',
    'Para empezar, debes crear una cuenta en <strong>MyProjectt</strong>' => '',
    'Reset' => '',
    'Search' => '',
    'Si deseas cambiar tu plan de suscripción, puedes hacerlo en tu área de usuario.' => '',
    'Si has olvidado tu contraseña puedes.' => '',
    'Si ya tienes una cuenta, simplemente ingresa en tu cuenta.' => '',
    'Una vez hayas igresado en tu nueva cuenta podrás empezara subir y compartir tus ficheros' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Actualizar' => '@@@@',
    'Actualizar {modelClass}: ' => '@@@@',
    'Borrar' => '@@@@',
    'Buscar' => '@@@@',
    'Crear' => '@@@@',
    'Crear {modelClass}' => '@@@@',
    'Resetear' => '@@@@',
    '¿Estás seguro de que deseas borrar este elemento?' => '@@@@',
];
