<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Category' => '',
    'Content' => '',
    'Content  ID' => '',
    'Contraseña' => '',
    'Controller' => '',
    'Course  Req' => '',
    'Creation  Date' => '',
    'Description' => '',
    'Email' => '',
    'Featured  Img' => '',
    'Header  Image' => '',
    'Header  Mask' => '',
    'Header  Text' => '',
    'Height' => '',
    'ID' => '',
    'Intro  Image' => '',
    'Intro  Text' => '',
    'Is  Home' => '',
    'Last  Modified' => '',
    'Layout' => '',
    'Layout  Section' => '',
    'Menu' => '',
    'Meta' => '',
    'Meta  Data' => '',
    'Method' => '',
    'Mime' => '',
    'Name' => '',
    'Nombre de usuario' => '',
    'Order' => '',
    'Owner' => '',
    'Page' => '',
    'Parent  Category' => '',
    'Parent  Page' => '',
    'Parent Item' => '',
    'Permalink' => '',
    'Position' => '',
    'Post  Category' => '',
    'Post  ID' => '',
    'Show  Bread  Crumbs' => '',
    'State' => '',
    'State  Name' => '',
    'Surname' => '',
    'Telephone' => '',
    'Template' => '',
    'Title' => '',
    'Type' => '',
    'Url' => '',
    'Version  ID' => '',
    'Widget  ID' => '',
    'Width' => '',
    'Wrap  Content' => '',
    'Nombre' => '@@@@',
];
